Added SingleChildScrollView/Updated Plugins and Made changes to alert Dialog to aid UX
Flutterwave/flutterwave-flutter pull request #16
Opened 2020-10-26 12:15 UTC by Itz-kwaz

I added a singleChildScrollView to make the view scrollable and make views that were previously invisible, visible.
also Removed debug checkedBanner by using the value of isdebugMode.

Removed the hex color plugin and used Color(0xFFFFFFF) instead.
Upgraded web_view_plugin.

2020-11-02 13:17 UTC, FredDominant commented
Hi @Itz-kwaz, thank you for your contribution. Could you look into the conflicts in this request? Looking forward to reviewing this again.

2020-11-02 13:23 UTC, Itz-kwaz commented
I'll surely look into the conflicts and resolve them. Thank you very much

2020-11-03 10:55 UTC, FredDominant commented on lib/widgets/bank_account_payment/bank_account_payment.dart
Hi @Itz-kwaz, I think it's better to leave these methods private. What do you think?

2020-11-03 10:56 UTC, FredDominant commented on lib/widgets/bank_transfer_payment/bank_transfer_payment.dart
>        this.loadingDialogContext = null;
Same for the methods in this file

2020-11-03 10:59 UTC, FredDominant commented on pubspec.yaml
> +version: 0.0.1
It's better to leave as `0.0.1`, we'll update this when we publish.

2020-11-03 11:01 UTC, FredDominant requested changes
Nice work @Itz-kwaz and thank you. Please check the comments, they basically request you to leave the private methods/fields as is.

2020-11-03 11:12 UTC, Itz-kwaz commented
Thank you very much @FredDominant, I'll make all the requested changes. If there is any other way I could contribute, please do let me know I'll be more than glad to do so.

2020-11-10 21:54 UTC, FredDominant approved these changes

2020-11-10 21:54 UTC, merged